#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: mysqldb
#spec:
#  selector:
#    matchLabels:
#      app: mysqldb
#  template:
#    metadata:
#      labels:
#        app: mysqldb
#    spec:
#      containers:
#        - name: mysqldb
#          image: mysql:8
#          env:
#            - name: MYSQL_ROOT_PASSWORD
#              value: "1234567"
#          ports:
#            - containerPort: 3307
kind: Deployment
apiVersion: apps/v1
metadata:
  name: discovery-server
  namespace: default
  uid: 5fc858a2-78e6-4bf2-bf08-17bda37f1787
  resourceVersion: '10281'
  generation: 2
  creationTimestamp: '2024-06-05T09:20:04Z'
  labels:
    app: discovery-server
  annotations:
    deployment.kubernetes.io/revision: '1'
  managedFields:
    - manager: dashboard
      operation: Update
      apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:replicas: {}
      subresource: scale
    - manager: kubectl-create
      operation: Update
      apiVersion: apps/v1
      time: '2024-06-05T09:20:04Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:app: {}
        f:spec:
          f:progressDeadlineSeconds: {}
          f:revisionHistoryLimit: {}
          f:selector: {}
          f:strategy:
            f:rollingUpdate:
              .: {}
              f:maxSurge: {}
              f:maxUnavailable: {}
            f:type: {}
          f:template:
            f:metadata:
              f:labels:
                .: {}
                f:app: {}
            f:spec:
              f:containers:
                k:{"name":"drive-n-share"}:
                  .: {}
                  f:image: {}
                  f:imagePullPolicy: {}
                  f:name: {}
                  f:resources: {}
                  f:terminationMessagePath: {}
                  f:terminationMessagePolicy: {}
              f:dnsPolicy: {}
              f:restartPolicy: {}
              f:schedulerName: {}
              f:securityContext: {}
              f:terminationGracePeriodSeconds: {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2024-06-05T09:44:08Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:deployment.kubernetes.io/revision: {}
        f:status:
          f:availableReplicas: {}
          f:conditions:
            .: {}
            k:{"type":"Available"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"Progressing"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
          f:observedGeneration: {}
          f:readyReplicas: {}
          f:replicas: {}
          f:updatedReplicas: {}
      subresource: status
spec:
  replicas: 3
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: discovery-server
    spec:
      containers:
        - name: drive-n-share
          image: zhizgov/drive-n-share:discovery-server-latest
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 2
  replicas: 3
  updatedReplicas: 3
  readyReplicas: 3
  availableReplicas: 3
  conditions:
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2024-06-05T09:20:27Z'
      lastTransitionTime: '2024-06-05T09:20:04Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "discovery-server-65b5c666d6" has successfully progressed.
    - type: Available
      status: 'True'
      lastUpdateTime: '2024-06-05T09:44:08Z'
      lastTransitionTime: '2024-06-05T09:44:08Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.