---
version: '3.8'
services:
## Message Broker
 zookeeper:
  image: confluentinc/cp-zookeeper:7.0.1
  container_name: zookeeper
#  ports:
#    - "2181:2181"
  environment:
    ZOOKEEPER_CLIENT_PORT: 2181
    ZOOKEEPER_TICK_TIME: 2000

 broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

##Auth & Auth
 keycloak-mysql:
    container_name: keycloak-mysql
    image: mysql:8
    volumes:
      - ./volume-data/mysql_keycloak_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
 keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.1
    command: [ "start-dev", "--import-realm" ]
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8181:8080"
    volumes:
      - ./docker/keycloak/realms/:/opt/keycloak/data/import/
    depends_on:
      - keycloak-mysql

 prometheus:
   image: prom/prometheus:v2.37.1
   container_name: prometheus
   restart: always
   ports:
     - "9090:9090"
   volumes:
     - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
#   depends_on:
#     - travel-service
#     - account-service
#     - api-gateway
#     - discovery-server

 grafana:
     image: grafana/grafana-oss:8.5.2
     container_name: grafana
     restart: always
     ports:
       - "3000:3000"
     links:
       - prometheus:prometheus
     volumes:
       - ./grafana:/var/lib/grafana
     environment:
       - GF_SECURITY_ADMIN_USER=admin
       - GF_SECURITY_ADMIN_PASSWORD=password

 mysql:
   image: mysql:8
   container_name: mysql
   environment:
     MYSQL_USER: root
     MYSQL_DB: dns_travel_service
     MYSQL_PASSWORD: 1234567
     MYSQL_ROOT_PASSWORD: root
   ports:
     - "5432:3306"

 travel-service:
       image: zhizgov/drive-n-share:travel-service-latest
       container_name: travel-service-container
       ports:
         - "8081:8081"
       environment:
         SPRING_DATASOURCE_URL: jdbc:mysql://localhost:5432/dns_travel_service?serverTimeZone=UTC
         SPRING_DATASOURCE_USERNAME: root
         SPRING_DATASOURCE_PASSWORD: 1234567
       depends_on:
         -  mysql