---
version: '3.8'
services:
## Message Broker
 zookeeper:
  image: confluentinc/cp-zookeeper:7.0.1
  container_name: zookeeper
  ports:
    - "2181:2181"
  environment:
    ZOOKEEPER_CLIENT_PORT: 2181
    ZOOKEEPER_TICK_TIME: 2000

 broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

##Auth & Auth
 keycloak-mysql:
    container_name: keycloak-mysql
    image: mysql:8
    volumes:
      - ./volume-data/mysql_keycloak_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
 keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.1
    command: [ "start-dev", "--import-realm" ]
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8181:8080"
    volumes:
      - ./docker/keycloak/realms/:/opt/keycloak/data/import/
    depends_on:
      - keycloak-mysql

 prometheus:
   image: prom/prometheus:v2.37.1
   container_name: prometheus
   restart: always
   ports:
     - "9090:9090"
   volumes:
     - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
   depends_on:
     - travel-service
#     - account-service
#     - api-gateway
#     - discovery-server

 grafana:
     image: grafana/grafana-oss:8.5.2
     container_name: grafana
     restart: always
     ports:
       - "3000:3000"
     links:
       - prometheus:prometheus
     volumes:
       - ./grafana:/var/lib/grafana
     environment:
       - GF_SECURITY_ADMIN_USER=admin
       - GF_SECURITY_ADMIN_PASSWORD=password

 mysql:
   image: mysql:8
   container_name: mysql
   environment:
#     MYSQL_DATABASE: dns_travel_service
     MYSQL_ROOT_PASSWORD: 1234567
   volumes:
     - mysql-db-data:/var/lib/mysql

# mysql-account:
#   image: mysql:8
#   container_name: mysql-account
#   environment:
#     MYSQL_DATABASE: dns_account_service
#     MYSQL_ROOT_PASSWORD: 1234567
#   ports:
#     - "3307:3307"
#   volumes:
#     - mysql-db-data:/var/lib/mysql





 travel-service:
       image: zhizgov/drive-n-share:travel-service-latest
       container_name: travel-service
#       build:
#         dockerfile: ./travel-service/Dockerfile
       ports:
         - "8081:8081"
       environment:
         EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka
         SPRING_DATASOURCE_URL: jdbc:mysql://mysql/dns_travel_service
         SPRING_PROFILES_ACTIVATE: docker
       depends_on:
         -  mysql

# account-service:
#     image: zhizgov/drive-n-share:account-service-latest
#     container_name: account-service
#     ports:
#       - "8082:8082"
#     environment:
#       SPRING_DATASOURCE_URL: jdbc:mysql://mysql/dns_account_service
#       SPRING_PROFILES_ACTIVATE: docker
#     depends_on:
#       - mysql
#
#
 api-gateway:
   image: zhizgov/drive-n-share:api-gateway-latest
   container_name: api-gateway
   #       build:
   #         dockerfile: ./travel-service/Dockerfile
   ports:
     - "8084:8084"
   environment:
     EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka
     SPRING_CLOUD_GATEWAY_ROUTES_0_URI: http://travel-service:8081
     SPRING_PROFILES_ACTIVATE: docker
   #         SPRING_DATASOURCE_USERNAME: root
   #         SPRING_DATASOURCE_PASSWORD: 1234567

 discovery-server:
   image: zhizgov/drive-n-share:discovery-server-latest
   container_name: discovery-server
   #       build:
   #         dockerfile: ./travel-service/Dockerfile
   ports:
     - "8761:8761"
   environment:
     SPRING_PROFILES_ACTIVATE: docker
   #         SPRING_DATASOURCE_USERNAME: root
   #         SPRING_DATASOURCE_PASSWORD: 1234567

 review-service:
   image: zhizgov/drive-n-share:review-service-latest
   container_name: review-service
   #       build:
   #         dockerfile: ./travel-service/Dockerfile
   ports:
     - "8083:8083"
   environment:
     SPRING_DATASOURCE_URL: jdbc:mysql://mysql/dns_review_service
     SPRING_DATASOURCE_USERNAME: root
     SPRING_DATASOURCE_PASSWORD: 1234567
   depends_on:
     - mysql

volumes:
  mysql-db-data: