---
version: '3.8'
services:
## Message Broker
 zookeeper:
  image: confluentinc/cp-zookeeper:7.0.1
  container_name: zookeeper
  ports:
    - "2181:2181"
  environment:
    ZOOKEEPER_CLIENT_PORT: 2181
    ZOOKEEPER_TICK_TIME: 2000

 broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1


 keycloak:
   image: quay.io/keycloak/keycloak:24.0.4
   ports:
     - "8282:8080"
   environment:
     - KEYCLOAK_ADMIN=admin
     - KEYCLOAK_ADMIN_PASSWORD=admin
   volumes:
     - keycloak_data:/opt/keycloak/data
     - keycloak_config:/opt/keycloak/conf
   command: ["start-dev"]



 prometheus:
   image: prom/prometheus:v2.37.1
   container_name: prometheus
   restart: always
   ports:
     - "9090:9090"
   volumes:
     - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
#   depends_on:
#     - travel_service
#     - account_service
#     - api_gateway

 grafana:
     image: grafana/grafana-oss:8.5.2
     container_name: grafana
     restart: always
     ports:
       - "3000:3000"
     links:
       - prometheus:prometheus
     volumes:
       - ./grafana:/var/lib/grafana
     environment:
       - GF_SECURITY_ADMIN_USER=admin
       - GF_SECURITY_ADMIN_PASSWORD=password

# mysqltravel:
#   ports:
#     - "3308:3308"
#   expose:
#     - "3308"
#   image: mysql:8
#   container_name: mysqltravel
#   environment:
#     MYSQL_DATABASE: 'dns_travel_service'
#     MYSQL_ROOT_PASSWORD: '1234567'
#     MYSQL_TCP_PORT: '3308'

#
# mysql_account:
#   ports:
#     - "3309:3309"
#   expose:
#     - "3309"
#   image: mysql:8
#   container_name: mysql_account
#   environment:
#     MYSQL_DATABASE: 'dns_account_service'
#     MYSQL_ROOT_PASSWORD: '1234567'
#     MYSQL_TCP_PORT: '3309'
#
#
# mysql_review:
#   ports:
#     - "3305:3305"
#   expose:
#     - "3305"
#   image: mysql:8
#   container_name: mysql_review
#   environment:
#     MYSQL_DATABASE: 'dns_review_service'
#     MYSQL_ROOT_PASSWORD: '1234567'
#     MYSQL_TCP_PORT: '3305'
#
#
#
#
# travelservice:
#       image: zhizgov/drive-n-share:travel-service-latest
#       container_name: travelservice
#       ports:
#         - "8081:8081"
#       environment:
##         EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery_server:8761/eureka
#         SPRING_DATASOURCE_URL: jdbc:mysql://mysqltravel:3308/dns_travel_service
#         SPRING_PROFILES_ACTIVATE: docker
#       depends_on:
#         -  mysqltravel

# account_service:
#     image: zhizgov/drive-n-share:account-service-latest
#     container_name: account_service
#     ports:
#       - "8082:8082"
#     environment:
#       SPRING_DATASOURCE_URL: jdbc:mysql://mysql_account:3309/dns_account_service
#       SPRING_PROFILES_ACTIVATE: docker
#     depends_on:
#       - mysql_account
#
#
# review_service:
#   image: zhizgov/drive-n-share:review-service-latest
#   container_name: review_service
#   #       build:
#   #         dockerfile: ./travel-service/Dockerfile
#   ports:
#     - "8083:8083"
#   environment:
#     SPRING_DATASOURCE_URL: jdbc:mysql://mysql_review:3305/dns_review_service
#     SPRING_DATASOURCE_USERNAME: root
#     SPRING_DATASOURCE_PASSWORD: 1234567
#   depends_on:
#     - mysql_review
#
# api_gateway:
#   image: zhizgov/drive-n-share:api-gateway-latest
#   container_name: api_gateway
#   ports:
#     - "8084:8084"
#   environment:
#     SPRING_PROFILES_ACTIVATE: docker



# discovery_server:
#   image: zhizgov/drive-n-share:discovery-server-latest
#   container_name: discovery_server
#   ports:
#     - "8761:8761"
#   environment:
#     SPRING_PROFILES_ACTIVATE: docker
#

volumes:
  keycloak_data:
  keycloak_config: