apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: review-service
  name: review-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: review-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/drive-n-share-default: "true"
        io.kompose.service: review-service
    spec:
      containers:
        - env:
            - name: SPRING_DATASOURCE_PASSWORD
              value: "1234567"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql_review:3305/dns_review_service
            - name: SPRING_DATASOURCE_USERNAME
              value: root
          image: zhizgov/drive-n-share:review-service-latest
          name: review-service
          ports:
            - containerPort: 8083
              hostPort: 8083
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
