apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: default
spec:
  selector:
    matchLabels:
      app: kafka
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
    spec:
      enableServiceLinks: false
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:latest
          ports:
            - containerPort: 9092
            - containerPort: 29092
          env:
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: PLAINTEXT
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: 35.204.179.156:2181
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"


# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   annotations:
#     kompose.cmd: kompose convert -f docker-compose.yaml
#     kompose.version: 1.31.2 (a92241f79)
#   creationTimestamp: null
#   labels:
#     io.kompose.service: broker
#   name: broker
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       io.kompose.service: broker
#   strategy: {}
#   template:
#     metadata:
#       annotations:
#         kompose.cmd: kompose convert -f docker-compose.yaml
#         kompose.version: 1.31.2 (a92241f79)
#       creationTimestamp: null
#       labels:
#         io.kompose.network/drive-n-share-default: "true"
#         io.kompose.service: broker
#     spec:
#       containers:
#         - env:
#             - name: KAFKA_ADVERTISED_LISTENERS
#               value: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
#             - name: KAFKA_BROKER_ID
#               value: "1"
#             - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
#               value: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
#             - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
#               value: "1"
#             - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
#               value: "1"
#             - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
#               value: "1"
#             - name: KAFKA_ZOOKEEPER_CONNECT
#               value: 34.90.241.154:2181
#           image: confluentinc/cp-kafka:7.0.1
#           name: broker
#           # ports:
#           #   - containerPort: 9092
#           #     hostPort: 9092
#           #     protocol: TCP
#           resources: {}
#       restartPolicy: Always
# status: {}
