apiVersion: v1
kind: Service
metadata:
  name: broker
  labels:
    app: broker
spec:
  selector:
    app: broker
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
  type: LoadBalancer
