apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqltravel
  namespace: default
spec:
  selector:
    matchLabels:
      app: mysqltravel
  replicas: 1
  template:
    metadata:
      labels:
        app: mysqltravel
    spec:
      containers:
        - name: mysqltravel
          image: mysql:8
          ports:
            - containerPort: 3308
          env:
            - name: MYSQL_DATABASE
              value: dns_travel_service
            - name: MYSQL_ROOT_PASSWORD
              value: "1234567"
            - name: MYSQL_TCP_PORT
              value: "3308"

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: mysqltravel
#   namespace: mysqltravel
# spec:
#   selector:
#     matchLabels:
#       app: mysqltravel
#   replicas: 1
#   template:
#     metadata:
      # labels:
      #   app: mysqltravel
#     spec:
#       containers:
#           image: mysql:8
#           env:
#             - name: MYSQL_DATABASE
#               value: dns_travel_service
#             - name: MYSQL_ROOT_PASSWORD
#               value: "1234567"
#             - name: MYSQL_TCP_PORT
#               value: 3308
#                         resources: {}
#       restartPolicy: Always
# status: {}
