apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: mysql-account
  name: mysql-account
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysql-account
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/drive-n-share-default: "true"
        io.kompose.service: mysql-account
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: dns_account_service
            - name: MYSQL_ROOT_PASSWORD
              value: "1234567"
            - name: MYSQL_TCP_PORT
              value: "3309"
          image: mysql:8
          name: mysql-account
          ports:
            - containerPort: 3309
              hostPort: 3309
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
