apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqltravel
  namespace: mysqltravel
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysqltravel
  strategy: {}
  template:
    metadata:
      labels:
        app: mysqltravel
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: dns_travel_service
            - name: MYSQL_ROOT_PASSWORD
              value: "1234567"
            - name: MYSQL_TCP_PORT
              value: "3308"
          image: mysql:8
          name: mysqltravel
          # ports:
          #   - containerPort: 3308
          #     hostPort: 3308
          #     protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: mysqltravel
#   namespace: mysqltravel
# spec:
#   selector:
#     matchLabels:
#       app: mysqltravel
#   replicas: 1
#   template:
#     metadata:
      # labels:
      #   app: mysqltravel
#     spec:
#       containers:
#           image: mysql:8
#           env:
#             - name: MYSQL_DATABASE
#               value: dns_travel_service
#             - name: MYSQL_ROOT_PASSWORD
#               value: "1234567"
#             - name: MYSQL_TCP_PORT
#               value: 3308
#                         resources: {}
#       restartPolicy: Always
# status: {}
