apiVersion: v1
kind: Service
metadata:
  name: mysqltravel
  labels:
    app: mysqltravel
spec:
  selector:
    app: mysqltravel
  ports:
    - protocol: TCP
      port: 3308
      targetPort: 3308
  type: LoadBalancer
