apiVersion: v1
kind: Service
metadata:
  name: mysqltravel
  labels:
    app: mysqltravel
spec:
  selector:
    app: mysqltravel
  ports:
    - containerPort: 3308
      hostPort: 3308
      protocol: TCP
  type: LoadBalancer
