# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   annotations:
#     kompose.cmd: kompose convert -f docker-compose.yaml
#     kompose.version: 1.31.2 (a92241f79)
#   creationTimestamp: null
#   labels:
#     io.kompose.service: mysqltravel
#   name: mysqltravel
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       io.kompose.service: mysqltravel
#   strategy: {}
#   template:
#     metadata:
#       annotations:
#         kompose.cmd: kompose convert -f docker-compose.yaml
#         kompose.version: 1.31.2 (a92241f79)
#       creationTimestamp: null
#       labels:
#         io.kompose.network/drive-n-share-default: "true"
#         io.kompose.service: mysqltravel
#     spec:
#       containers:
#         - env:
#             - name: MYSQL_DATABASE
#               value: dns_travel_service
#             - name: MYSQL_ROOT_PASSWORD
#               value: "1234567"
#             - name: MYSQL_TCP_PORT
#               value: "3308"
#           image: mysql:8
#           name: mysqltravel
#           # ports:
#           #   - containerPort: 3308
#           #     hostPort: 3308
#           #     protocol: TCP
#           resources: {}
#       restartPolicy: Always
# status: {}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqltravel
  namespace: mysqltravel
spec:
  selector:
    matchLabels:
      app: mysqltravel
  replicas: 1
  template:
    metadata:
      labels:
        app: mysqltravel
    spec:
      containers:
        - name: mysqltravel
          image: mysql:8
          ports:
            - containerPort: 3308
        - env:
            - name: MYSQL_DATABASE
              value: dns_travel_service
            - name: MYSQL_ROOT_PASSWORD
              value: "1234567"
            - name: MYSQL_TCP_PORT
              value: "3308"
