apiVersion: apps/v1
kind: Deployment
metadata:
  name: travel-service
  namespace: default
spec:
  selector:
    matchLabels:
      app: travel-service
  replicas: 1
  template:
    metadata:
      labels:
        app: travel-service
    spec:
      containers:
        - name: travel-service
          image: zhizgov/drive-n-share:travel-service-latest
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://34.91.34.252:3308/dns_travel_service
            - name: SPRING_PROFILES_ACTIVATE
              value: docker
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   annotations:
#     kompose.cmd: kompose convert -f docker-compose.yaml
#     kompose.version: 1.31.2 (a92241f79)
#   creationTimestamp: null
#   labels:
#     io.kompose.service: travelservice
#   name: travelservice
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       io.kompose.service: travelservice
#   strategy: {}
#   template:
#     metadata:
#       annotations:
#         kompose.cmd: kompose convert -f docker-compose.yaml
#         kompose.version: 1.31.2 (a92241f79)
#       creationTimestamp: null
#       labels:
#         io.kompose.network/drive-n-share-default: "true"
#         io.kompose.service: travelservice
#     spec:
#       containers:
#         - env:
#             - name: SPRING_DATASOURCE_URL
#               value: jdbc:mysql://34.32.236.116:3308/dns_travel_service
#             - name: SPRING_PROFILES_ACTIVATE
#               value: docker
#             # - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
#             #   value: 34.91.116.40:9092
#           image: zhizgov/drive-n-share:travel-service-latest
#           name: travelservice
#           # ports:
#           #   - containerPort: 8081
#           #     hostPort: 8081
#           #     protocol: TCP
#           # resources:
#             # limits:
#             #   cpu: "1000m"
#             #   memory: "500Mi"

#       restartPolicy: Always
# status: {}
