apiVersion: v1
kind: Service
metadata:
  name: travelservice
  labels:
    app: travelservice
spec:
  selector:
    app: travelservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: LoadBalancer
